---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/project-id: php-01hhmj81fhp
  name: ipa-aspc-gc-ca
spec:
  dnsName: ipa.aspc.gc.ca.
  dnssecConfig:
    defaultKeySpecs:
    - algorithm: rsasha256
      keyLength: 2048
      keyType: keySigning
      kind: dns#dnsKeySpec
    - algorithm: rsasha256
      keyLength: 1024
      keyType: zoneSigning
      kind: dns#dnsKeySpec
    kind: dns#managedZoneDnsSecConfig
    nonExistence: nsec3
    state: "on"
  resourceID: ipa-aspc-gc-ca
  visibility: public
...