apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/project-id: php-01hhmj81fhp
    cnrm.cloud.google.com/deletion-policy: abandon
  name: ouvert-aspc-gc-ca
spec:
  dnsName: ouvert.aspc.gc.ca.
  dnssecConfig:
    defaultKeySpecs:
      - algorithm: rsasha256
        keyLength: 2048
        keyType: keySigning
        kind: dns#dnsKeySpec
      - algorithm: rsasha256
        keyLength: 1024
        keyType: zoneSigning
        kind: dns#dnsKeySpec
    kind: dns#managedZoneDnsSecConfig
    nonExistence: nsec3
    state: "on"
  resourceID: ouvert-aspc-gc-ca
  visibility: public
