gcloud dns --project=php-01hhmj81fhp managed-zones create alpha-phac-gc-ca --description="" --dns-name="alpha.phac.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create alpha-aspc-gc-ca --description="" --dns-name="alpha.aspc.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create alpha-phac-aspc-gc-ca --description="" --dns-name="alpha.phac-aspc.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create beta-phac-gc-ca --description="" --dns-name="beta.phac.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create beta-aspc-gc-ca --description="" --dns-name="beta.aspc.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create beta-phac-aspc-gc-ca --description="" --dns-name="beta.phac-aspc.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create data-phac-gc-ca --description="" --dns-name="data.phac.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create donnes-aspc-gc-ca --description="" --dns-name="donnes.aspc.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create data-donnes-phac-aspc-gc-ca --description="" --dns-name="data-donnes.phac-aspc.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create api-phac-gc-ca --description="" --dns-name="api.phac.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create ipa-aspc-gc-ca --description="" --dns-name="ipa.aspc.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create api-ipa-phac-aspc-gc-ca --description="" --dns-name="api-ipa.phac-aspc.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create open-phac-gc-ca --description="" --dns-name="open.phac.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create ouvert-aspc-gc-ca --description="" --dns-name="ouvert.aspc.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
gcloud dns --project=php-01hhmj81fhp managed-zones create open-ouvert-phac-aspc-gc-ca --description="" --dns-name="open-ouvert.phac-aspc.gc.ca." --visibility="public" --dnssec-state="on" --log-dns-queries
