# root-sync.yaml
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: phac-dns-root-sync
  namespace: config-management-system
spec:
  sourceType: git
  sourceFormat: unstructured
  git:
    repo: https://github.dev/PHACDataHub/phac-dns
    dir: dns
    branch: main
    gcpServiceAccountEmail: 545971386665-compute@developer.gserviceaccount.com 
    # fix
