# root-sync.yaml
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  git:
    auth: none
    branch: main
    dir: dns-records
    repo: https://github.com/PHACDataHub/phac-dns.git
  sourceFormat: unstructured
  sourceType: git
