# Ref: https://cloud.google.com/config-connector/docs/how-to/install-namespaced#configure_to_run_in_namespaced_mode
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  # the name is restricted to ensure that there is only one 
  # ConfigConnector resource installed in your cluster
  name: configconnector.core.cnrm.cloud.google.com
spec:
 mode: namespaced
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnrm-system
  annotations:
    cnrm.cloud.google.com/project-id: php-01hhmj81fhp
spec: {}
status: {}
---
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  # you can only have one ConfigConnectorContext per namespace
  name: configconnectorcontext.core.cnrm.cloud.google.com
  namespace: cnrm-system
spec:
  googleServiceAccount: sa-php-01hhmj81fhp-phac-dns@php-01hhmj81fhp.iam.gserviceaccount.com
