apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: atip-dlp-alpha-phac-gc-ca
  namespace: config-control
  annotations:
    sourceCodeRepository: "https://github.com/PHACDataHub/atip-dlp/"
    cnrm.cloud.google.com/deletion-policy: abandon
  labels:
    controlled-by: "phac-dns"
    project-name: "atip-dlp"
    project-id: "hcx-01hsvjxh7wf"
spec:
  name: "atip-dlp.alpha.phac.gc.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: alpha-phac-gc-ca
  rrdatas:
    - ns-cloud-e1.googledomains.com.
    - ns-cloud-e2.googledomains.com.
    - ns-cloud-e3.googledomains.com.
    - ns-cloud-e4.googledomains.com.
