apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: backstage-alpha-phac-aspc-gc-ca
  namespace: dns
  annotations:
    sourceCodeRepository: "https://github.com/PHACDataHub/sci-portal"
  labels:
    controlled-by: "phac-dns"
    project-name: "sci-portal"
    project-id: "pht-01hsv4d2m0n"
spec:
  name: "backstage.alpha.phac-aspc.gc.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: alpha-phac-aspc-gc-ca
  rrdatas:
    - ns-cloud-a1.googledomains.com.
    - ns-cloud-a2.googledomains.com.
    - ns-cloud-a3.googledomains.com.
    - ns-cloud-a4.googledomains.com.
