apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: data-readiness-repository-data-phac-gc-ca
  namespace: dns
  annotations:
    sourceCodeRepository: "https://github.com/PHACDataHub/data-readiness-repository/"
    cnrm.cloud.google.com/deletion-policy: abandon
  labels:
    controlled-by: "phac-dns"
    project-name: "data-readiness-repository"
    project-id: "pht-01hp2gskb15"
spec:
  name: "data-readiness-repository.data.phac.gc.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: data-phac-gc-ca
  rrdatas:
    - ns-cloud-d1.googledomains.com.
    - ns-cloud-d2.googledomains.com.
    - ns-cloud-d3.googledomains.com.
    - ns-cloud-d4.googledomains.com.
