apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: geocoder-alpha-phac-gc-ca
  namespace: config-control
  annotations:
    sourceCodeRepository: "https://github.com/PHACDataHub/pelias-canada/"
    cnrm.cloud.google.com/deletion-policy: abandon
  labels:
    controlled-by: "phac-dns"
    project-name: "pelias-geocoder"
    project-id: "phx-01ha7rezhv"
spec:
  name: "geocoder.alpha.phac.gc.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: alpha-phac-gc-ca
  rrdatas:
    - ns-cloud-b1.googledomains.com.
    - ns-cloud-b2.googledomains.com.
    - ns-cloud-b3.googledomains.com.
    - ns-cloud-b4.googledomains.com.
