apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: ky-alpha-phac-gc-ca
  namespace: config-control
  annotations:
    sourceCodeRepository: "https://github.com/tcaky/getting-rusty"
  labels:
    controlled-by: "phac-dns"
    project-name: "test-ky"
    #project-id: ""
spec:
  name: "ky.alpha.phac.gc.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: alpha-phac-gc-ca
  rrdatas:
    - ns-cloud-d1.googledomains.com.
    - ns-cloud-d2.googledomains.com.
    - ns-cloud-d3.googledomains.com.
    - ns-cloud-d4.googledomains.com.
