apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: llm-alpha-phac-gc-ca
  namespace: dns
  annotations:
    sourceCodeRepository: "https://github.com/PHACDataHub/llm-playground"
    cnrm.cloud.google.com/deletion-policy: abandon
  labels:
    controlled-by: "phac-dns"
    project-name: "data-science-llm"
    project-id: "phx-datasciencellm"
spec:
  name: "llm.alpha.phac.gc.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: alpha-phac-gc-ca
  rrdatas:
    - ns-cloud-c1.googledomains.com.
    - ns-cloud-c2.googledomains.com.
    - ns-cloud-c3.googledomains.com.
    - ns-cloud-c4.googledomains.com.
