apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: observatory-alpha-phac-gc-ca
  namespace: dns
  annotations:
    sourceCodeRepository: "https://github.com/PHACDataHub/ruok-service-autochecker"
  labels:
    controlled-by: "phac-dns"
    project-name: "phx-siddharthahaldar"
    project-id: "phx-01h7dnj5j46f52sev8akqd9m7g"
spec:
  name: "observatory.alpha.phac.gc.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: alpha-phac-gc-ca
  rrdatas:
    - ns-cloud-d1.googledomains.com.
    - ns-cloud-d2.googledomains.com.
    - ns-cloud-d3.googledomains.com.
    - ns-cloud-d4.googledomains.com.
