apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: shiny-alpha-phac-aspc-gc-ca
  namespace: config-control
  annotations:
    projectName: "django-shiny"
    projectId: "pht-01hhmqtnrpf"
    sourceCodeRepository: "https://github.com/PHACDataHub/django-shiny"
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  name: "shiny.alpha.phac-aspc.gc.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: alpha-phac-aspc-gc-ca
  rrdatas:
    - ns-cloud-a1.googledomains.com.
    - ns-cloud-a2.googledomains.com.
    - ns-cloud-a3.googledomains.com.
    - ns-cloud-a4.googledomains.com.
