apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: shiny-alpha-phac-aspc-gc-ca
  namespace: config-control
  annotations:
    projectName: "django-shiny"
    sourceCodeRepository: "https://github.com/PHACDataHub/django-shiny"
spec:
  name: "shiny.alpha.phac-aspc.gc.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: alpha-phac-aspc-gc-ca
  rrdatas:
    - ns-cloud-e1.googledomains.com.
    - ns-cloud-e2.googledomains.com.
    - ns-cloud-e3.googledomains.com.
    - ns-cloud-e4.googledomains.com.
