apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  interval: 2m
  path: ./k8s/clusters/infrastructure/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

