---
name: Yaml Linting
on:
  pull_request:
    paths:
      - 'dns-records/*.yaml'
      - 'k8s/components/infrastructure/*.yaml'
jobs:
  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint
...
